dist: xenial
sudo: required

language: java
jdk:
  - openjdk8

services:
  - docker

before_install:
  # install conntrack which is required for minikube
  - sudo apt-get -qq -y install conntrack
  # install nsenter which is required for port forwarding
  - travis/ubuntu-compile-nsenter.sh && sudo cp $HOME/nsenter/util-linux-2.30.2/nsenter /usr/bin
  - travis/install-start-minikube.sh && export PATH=`pwd`:${PATH} # set minikube and kubectl to PATH
  - kubectl get all --all-namespaces

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/nsenter

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: test
      env: [ NAME=all-in-one ]
      script: ./mvnw clean verify -Pall-in-one

    - env: [ NAME=cassandra ]
      script: ./mvnw clean verify -Pcassandra

    - env: [ NAME=elasticsearch ]
      script: ./mvnw clean verify -Pelasticsearch

after_script:
  - docker images --no-trunc=true

env:
  global:
