dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8

before_install:
# install nsenter which is required for port forwarding
  - travis/ubuntu-compile-nsenter.sh && sudo cp .tmp/util-linux-2.24.1/nsenter /usr/bin
  - travis/install-start-minikube.sh && export PATH=`pwd`:${PATH} # set minikube and kubectl to PATH
  - kubectl get all --all-namespaces

cache:
  directories:
  - $HOME/.m2/repository

script:
  - ./mvnw clean verify -Pe2e

after_script:
  - docker images --no-trunc=true

env:
  global:
