dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

script:
  # compile java sources/tests, note that this does not run any tests
  - ./mvnw clean compile

env:
  global:
